package Exception;

public class ExcepTest {

    public static void main(String[] args) {
        try {
            int a[] = new int[2]; //Mendeklarasi integer array dengan jumlah elemen 2
            System.out.println("Access element three: " +a[3]);
            //mencoba mengakses indeks ke 3 dari array a yang hanya memiliki 2 indeks (OutOfBounds)
        } catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Exception thrown: " +e); 
            //kemudian exceptio akan diambil oleh catch dan mencetak pesan "Out of the block"
        }
        System.out.println("Out of the block");
    }
}
